CREATE TABLE insurance_claims (
	months_as_customer INTEGER,
	age INTEGER,
	policy_number INTEGER,
	policy_bind_date DATE,
	policy_state VARCHAR(2),
	policy_csl VARCHAR(10),
	policy_deductable INTEGER,
	policy_annual_premium DECIMAL,
	umbrella_limit INTEGER,
	insured_zip INTEGER,
	insured_sex VARCHAR(6),
	insured_education_level VARCHAR(15),
	insured_occupation VARCHAR(25),
	insured_hobbies VARCHAR(15),
	insured_relationship VARCHAR(15),
	capital_gains INTEGER,
	capital_loss INTEGER,
	incident_date DATE,
	incident_type VARCHAR(25),
	collision_type VARCHAR(20),
	incident_severity VARCHAR(20),
	authorities_contacted VARCHAR(10),
	incident_state VARCHAR(2),
	incident_city VARCHAR(15),
	incident_location VARCHAR(25),
	incident_hour_of_the_day INTEGER,
	number_of_vehicles_involved INTEGER,
	property_damage VARCHAR(3),
	bodily_injuries INTEGER,
	witnesses INTEGER,
	police_report_available VARCHAR(3),
	total_claim_amount INTEGER,
	injury_claim INTEGER,
	property_claim INTEGER,
	vehicle_claim INTEGER,
	auto_make VARCHAR(10),
	autauto_model VARCHAR(15),
	auto_year INTEGER,
	fraud_reported VARCHAR(1),
	PRIMARY KEY (policy_number)
);

DROP TABLE insurance_claims;

SELECT * from insurance_claims;